# https://taskfile.dev
# A modern replacement of Makefile
version: '3'

vars:
  REPO_ABS_ROOT_PATH:
    sh: git rev-parse --show-toplevel
  ORBS_CALLER_ROOT_PATH:
    sh: realpath "{{.REPO_ABS_ROOT_PATH}}/.."
  GIT_REPO:
    sh: git config --get remote.origin.url | sed -e 's#^.*:##' -e 's#.git$##' -e 's#//github.com/*##'
  REPO_NAME:
    sh: echo {{.GIT_REPO}} | sed -e 's#^.*/##'

silent: true

tasks:
  debug:
    desc: Run all debug tasks
    cmds:
    - echo -e "\n📒 {{.TASK}}"
    - task: debug:resolve_vars

  debug:resolve_vars:
    desc: Output few things which can help debugging
    cmds:
    - echo -e "\n📒 {{.TASK}}"
    - echo "Absolute root path":" {{.REPO_ABS_ROOT_PATH}}"
    - echo "Orbs caller root path":" {{.ORBS_CALLER_ROOT_PATH}}"
    - echo "Git repo":" {{.GIT_REPO}}"
    - echo "Repo name":" {{.REPO_NAME}}"

  all:
    desc: Run all security scanners
    run: once
    cmds:
    - echo -e "\n📒 {{.TASK}}"
    - if [[ "{{.CLI_ARGS}}" == *"sarif"* ]]; then mkdir -p sarif-reports; fi
    - task: filesystem:grype
    - task: secret:gitleaks  # scan:ignore

  filesystem:grype:
    desc: Run Grype (Filesystem Vulnerability Scanner)
    cmds:
    - echo -e "\n📒 {{.TASK}}"
    - plugin_name="grype"; asdf plugin add "${plugin_name}" || true; asdf install "${plugin_name}" $(asdf current "${plugin_name}" | tr -s ' ' | cut -d' ' -f2)
    - grype "dir:." --output table --config {{.REPO_ABS_ROOT_PATH}}/.security/grype.yaml

  # Remove the --no-git flag if you want gitleaks to make a deep scan on the entire history of the repo
  secret:gitleaks:
    desc: Run Gitleaks
    cmds:
    - echo -e "\n📒 {{.TASK}}"
    - |
      [[ "${GITHUB_ACTIONS}" == 'true' ]] && redact="--redact"
      if [[ "{{.CLI_ARGS}}" == *"sarif"* ]]; then
        docker run --rm --volume "{{.ORBS_CALLER_ROOT_PATH}}:/work" zricethezav/gitleaks:latest detect --no-git --exit-code 1 -v ${redact} --report-format "sarif" --report-path "sarif-reports/gitleaks-report.sarif" --source="/work" --config /work/{{.REPO_NAME}}/.security/credscan-config.toml
      else
        docker run --rm --volume "{{.ORBS_CALLER_ROOT_PATH}}:/work" zricethezav/gitleaks:latest detect --no-git --exit-code 1 -v ${redact} --source="/work" --config /work/{{.REPO_NAME}}/.security/credscan-config.toml
      fi
