name: 'Notifier'

on:
  repository_dispatch:
    types: [slack-notification]
  workflow_call:
    inputs:
      type:
        required: false
        type: string
        default: 'build'
      ref:
        required: true
        type: string
      sha:
        required: true
        type: string
      color:
        required: true
        type: string
      title:
        required: true
        type: string
      message:
        required: true
        type: string
    # secrets:
    #   token:
    #     required: true

jobs:
  slack_notification:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: 'Send Slack Security Notification'
        if: github.event.client_payload.type == 'alert' || inputs.type == 'alert'
        # uses: rtCamp/action-slack-notify@v2.2.0
        # ^^ to be used as soon as PR https://github.com/rtCamp/action-slack-notify/pull/79 gets approved by the rtCamp maintainer
        uses: bogaertg/action-slack-notify@95fbd80cf578cd856020cc7729d2ed81f9652064
        env:
          SLACK_ICON: 'https://octodex.github.com/images/Sentrytocat_octodex.jpg'
          SLACK_WEBHOOK: ${{ secrets.SLACK_ALERTS_WEBHOOK }}
          SLACK_USERNAME: ${{ secrets.SLACK_USERNAME || 'Platform Team' }}
          SLACK_COLOR: ${{ github.event.client_payload.color || inputs.color }}
          SLACK_TITLE: ${{ github.event.client_payload.title || inputs.title }}
          SLACK_MESSAGE: ${{ github.event.client_payload.message || inputs.message }}
          # SLACK_COLOR: ${{ inputs.color }}
          # SLACK_TITLE: ${{ inputs.title }}
          # SLACK_MESSAGE: ${{ inputs.message }}
          MSG_MINIMAL: Commit
          SLACK_FOOTER: ''
      - name: 'Send Slack Notification to Raise Awareness'
        if: github.event.client_payload.type == 'awareness'
        # uses: rtCamp/action-slack-notify@v2.2.0
        # ^^ to be used as soon as PR https://github.com/rtCamp/action-slack-notify/pull/79 gets approved by the rtCamp maintainer
        uses: bogaertg/action-slack-notify@95fbd80cf578cd856020cc7729d2ed81f9652064
        env:
          SLACK_ICON: 'https://octodex.github.com/images/collabocats.jpg'
          SLACK_WEBHOOK: ${{ secrets.SLACK_AWARENESS_WEBHOOK || secrets.SLACK_BUILD_WEBHOOK }}
          SLACK_USERNAME: ${{ secrets.SLACK_USERNAME || 'Platform Team' }}
          SLACK_COLOR: ${{ github.event.client_payload.color }}
          SLACK_TITLE: ${{ github.event.client_payload.title }}
          SLACK_MESSAGE: ${{ github.event.client_payload.message }}
          MSG_MINIMAL: Commit
          SLACK_FOOTER: ''
      - name: 'Send Slack Build Completion Notification'
        if: github.event.client_payload.type == 'build'
        # uses: rtCamp/action-slack-notify@v2.2.0
        # ^^ to be used as soon as PR https://github.com/rtCamp/action-slack-notify/pull/79 gets approved by the rtCamp maintainer
        uses: bogaertg/action-slack-notify@95fbd80cf578cd856020cc7729d2ed81f9652064
        env:
          SLACK_ICON: 'https://octodex.github.com/images/constructocat2.jpg'
          SLACK_WEBHOOK: ${{ secrets.SLACK_BUILD_WEBHOOK }}
          SLACK_USERNAME: ${{ secrets.SLACK_USERNAME || 'Platform Team' }}
          SLACK_COLOR: ${{ github.event.client_payload.color }}
          SLACK_TITLE: ${{ github.event.client_payload.title }}
          SLACK_MESSAGE: ${{ github.event.client_payload.message }}
          MSG_MINIMAL: Commit
          SLACK_FOOTER: ''
      - name: 'Send Slack Housekeeping Notification'
        if: github.event.client_payload.type == 'housekeeping'
        # uses: rtCamp/action-slack-notify@v2.2.0
        # ^^ to be used as soon as PR https://github.com/rtCamp/action-slack-notify/pull/79 gets approved by the rtCamp maintainer
        uses: bogaertg/action-slack-notify@95fbd80cf578cd856020cc7729d2ed81f9652064
        env:
          SLACK_ICON: 'https://octodex.github.com/images/mona-the-rivetertocat.png'
          SLACK_WEBHOOK: ${{ secrets.SLACK_HOUSEKEEPING_WEBHOOK || secrets.SLACK_BUILD_WEBHOOK }}
          SLACK_USERNAME: ${{ secrets.SLACK_USERNAME || 'Platform Team' }}
          SLACK_COLOR: ${{ github.event.client_payload.color }}
          SLACK_TITLE: ${{ github.event.client_payload.title }}
          SLACK_MESSAGE: ${{ github.event.client_payload.message }}
          MSG_MINIMAL: Commit
          SLACK_FOOTER: ''
